[package]
name = "udpDuplicator"
version = "0.1.0"
authors = ["name <aaa@aaaa.aaa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "2.33.0"
crc32fast = "1.2.0"